import Angle from './Angle';
import RemoveBackground from './RemoveBackground';
import Background from './Background';
import Enhance from './Enhance';
import Extract from './Extract';
import Gravity from './Gravity';
import Recolor from './Recolor';
import Restore from './Restore';
import Remove from './Remove';
export  {Angle,RemoveBackground,Background,Enhance,Extract,Gravity,Recolor,Restore,Remove};